from recog import *


ancest = {
  # main
  "Antarctica": main.Antarctica.show(),
  "United Nation Of Antarctica": main.Antarctica.show("United Nation of Antarctica"),
  "Nation Of Antarctica": main.Antarctica,
  "ATC": main.Antarctica.hide(),
  "ATCA": main.Antarctica.hide(),
  "Self": main.Antarctica,
  "Country": main.Antarctica,
  "Origin": main.Antarctica,
  "Us": main.Antarctica,
  "Here": main.Antarctica,
  "Home": main.Antarctica,
  "Continent Of Antarctica": main.Continent.show("Continent of Antarctica"),
  "Continent": main.Continent,
  "Mainland": main.Continent,

  "Foundation Of Antarctica": main.Foundation.show("Foundation of Antarctica"),
  "Foundation": main.Foundation,
  "Government": main.Foundation,
  "Antarctican Trust": main.Trust.show(),
  "Trust": main.Trust,
  "Charity": main.Trust,

  "SAME": main.SAME.show(),
  "Language": main.SAME,
  "Languages": main.SAME,
  "Communication": main.SAME,
  "Dialect": main.SAME,

  "7 Marvels Of Antarctica": main.Marvels.show("7 Marvels of Antarctica"),
  "7 Marvels": main.Marvels,
  "Marvels": main.Marvels,
  "Marvel": main.Marvels,
  "Wonders Of Antarctica": main.Marvels,
  "Wonders Of The World": main.Marvels,
  "Wonders": main.Marvels,
  "Wonder": main.Marvels,

  # time
  "Antarctican Calendar": time.Calendar.show(),
  "Calendar": time.Calendar,
  "Year": time.Calendar,
  "Decant": time.Decant.show(),
  "Month": time.Decant,
  "Vedecant": time.Decant,
  "Adecant": time.Decant,
  "Sedecant": time.Decant,
  "Decate": time.Decate.show(),
  "Date": time.Decate,
  "Septan": time.Septan.show(),
  "Week": time.Septan,
  "Secta": time.Septan,
  "Septate": time.Septate.show(),
  "Day": time.Septate,
  "Weekend": time.Septan,
  "Weekday": time.Septan,

  "Arteria": time.decants.Arteria.show(),
  "1": time.decants.Arteria,
  "A1": time.decants.Arteria.hide(),
  "Vitida": time.decants.Vitida.show(),
  "2": time.decants.Vitida,
  "V1": time.decants.Vitida.hide(),
  "Arrikta": time.decants.Arrikta.show(),
  "3": time.decants.Arrikta,
  "A2": time.decants.Arrikta.hide(),
  "Valia": time.decants.Valia.show(),
  "4": time.decants.Valia,
  "V2": time.decants.Valia.hide(),
  "Aliquanda": time.decants.Aliquanda.show(),
  "5": time.decants.Aliquanda,
  "A3": time.decants.Aliquanda.hide(),
  "Verita": time.decants.Verita.show(),
  "6": time.decants.Verita,
  "V3": time.decants.Verita.hide(),
  "Arteva": time.decants.Arteva.show(),
  "7": time.decants.Arteva,
  "A4": time.decants.Arteva.hide(),
  "Vepida": time.decants.Vepida.show(),
  "8": time.decants.Vepida,
  "V4": time.decants.Vepida.hide(),
  "Aeva": time.decants.Aeva.show(),
  "9": time.decants.Aeva,
  "A5": time.decants.Aeva.hide(),
  "Verena": time.decants.Verena.show(),
  "10": time.decants.Verena,
  "V5": time.decants.Verena.hide(),

  "Discovery Day": time.fest.Discovery.show(),
  "Tersolle": time.fest.Tersolle.show(),
  "Invict Day": time.fest.Invict.show(),
  "Falcon's Noon": time.fest.Falcon.show(),
  "Falcons Noon": time.fest.Falcon,
  "Falcons' Noon": time.fest.Falcon.hide(),

  # geo
  "District": geo.dist.District.show(),
  "Aventurina District": geo.dist.Aventurina.show(),
  "Aventurina": geo.dist.Aventurina,
  "Atalla District":geo.dist.Atalla.show(),
  "Atalla": geo.dist.Atalla,
  "Ascerta District": geo.dist.Ascerta.show(),
  "Ascerta": geo.dist.Ascerta,

  "Titeria District": geo.dist.Titeria.show(),
  "Titeria": geo.dist.Titeria,
  "Divelda District": geo.dist.Divelda.show(),
  "Divelda": geo.dist.Divelda,
  "Dessica District": geo.dist.Dessica.show(),
  "Dessica": geo.dist.Dessica,
  "Discenda District": geo.dist.Discenda.show(),
  "Discenda": geo.dist.Discenda,

  "Ross City": geo.city.Ross.show(),
  "Capital City": geo.city.Ross,
  "Capital": geo.city.Ross,
  "Archadia": geo.city.Archadia.show(),
  "Archadia City": geo.city.Archadia,
  "Atla": geo.city.Atla.show(),
  "Atla City": geo.city.Atla,
  "Aleta": geo.city.Aleta.show(),
  "Aleta City": geo.city.Aleta,
  "Axona": geo.city.Axona.show(),
  "Axona City": geo.city.Axona,

  "Novada": geo.city.Novada.show(),
  "Novada City": geo.city.Novada,
  "Teneca": geo.city.Teneca.show(),
  "Teneca City": geo.city.Teneca,
  "Yena": geo.city.Yena.show(),
  "Yena City": geo.city.Yena,
  "Escharcha": geo.city.Escharcha.show(),
  "Escharcha City": geo.city.Escharcha,
  "Panaxa": geo.city.Panaxa.show(),
  "Panaxa City": geo.city.Panaxa,
  "Vanqua": geo.city.Vanqua.show(),
  "Vanqua City": geo.city.Vanqua,
  "Helada": geo.city.Helada.show(),
  "Helada City": geo.city.Helada,

  # locations
  "CARROT": loc.Carrot.show(),
  "Control Tower": loc.Carrot,
  "Rubicon Valley": loc.Rubicon.show(),

  # education
  "Education System Of Antarctica": edu.System.show("Education System of Antarctica"),
  "Education in Antarctica": edu.System,
  "Education": edu.System,
  "Foundational Education": edu.Foundational.show(),
  "Lower Education": edu.Lower.show(),
  "Prime Education": edu.Prime.show(),
  "Higher Education": edu.Higher.show(),

  "Scott University": edu.Scott.show(),
  "Amundsen College": edu.Amundsen.show(),
  "Ross Academy": edu.Ross.show(),
  "NIOTECH": edu.Nio.show("NioTech"),
  "National Institute Of Technology": edu.Nio,
  "ROAG": edu.ROAG.show(),
  "Royal Academy Of Geoengineering": edu.ROAG,
  "LAKARA": edu.Lakara.show("Lakara"),
  "Lazarev And Klenova Academy Of Research And Advancement": edu.Lakara,
  "Lazarev & Klenova Academy Of Research & Advancement": edu.Lakara.hide(),
  "Evelyn Institute Of Exploration": edu.Evelyn.show("Evelyn Institute of Exploration"),
  "ISAB": edu.ISAB.show(),
  "Ingra-Shackleton Academy Of Bioengineering": edu.ISAB,
  "Ingra Shackleton Academy Of Bioengineering": edu.ISAB.hide(),

  # tech
  "The Geosphere": tech.Geosphere.show(),
  "Geosphere": tech.Geosphere,
  "Biosphere": tech.Geosphere,
  "Sphere": tech.Geosphere,
  "Dome": tech.Geosphere,
  "The Dome": tech.Geosphere,
  "The Geomatrix": tech.Geomatrix.show(),
  "Geomatrix": tech.Geomatrix,

  "CORE": tech.core.CORE.show(),
  "A-CORE": tech.core.A.show(),
  "Acore": tech.core.A,
  "V-CORE": tech.core.V.show(),
  "Vcore": tech.core.V,
  "E-CORE": tech.core.E.show(),
  "Ecore": tech.core.E,
  "S-CORE": tech.core.S.show(),
  "Score": tech.core.S,
  "W-CORE": tech.core.W.show(),
  "Wcore": tech.core.W,
  "I-CORE": tech.core.I.show(),
  "Icore": tech.core.I,

  # medi
  "NICCOLU": medi.Niccolu.show("Niccolu"),
  "CLOMS": medi.CLOMS.show(),
  "Concerningly Low Metabolism Syndrome": medi.CLOMS,
  "EDAICS": medi.EDAICS.show(),
  "Energy Deficient AutoImmune Collapse Syndrome": medi.EDAICS,

  # military
  "Terra Forza": mili.div.Terra.show(),
  "Ground Force": mili.div.Terra,
  "Ground": mili.div.Terra,
  "Nava Corza": mili.div.Nava.show(),
  "Naval Force": mili.div.Nava,
  "Navy": mili.div.Nava,
  "Aera Norza": mili.div.Aera.show(),
  "Air Force": mili.div.Aera,
  "Aeronauts": mili.div.Aera,
  "Ginga Ranza": mili.div.Ginga.show(),
  "Space Force": mili.div.Ginga,
  "ASDF": mili.div.ASDF.show(),
  "Antarctican Special Defence Force": mili.div.ASDF,
  "Antarctican Special Defense Force": mili.div.ASDF.hide(),
  "Special Forces": mili.div.ASDF,
  "Special Force": mili.div.ASDF.hide(),

  "ASMR": mili.awards.ASMR.show(),
  "RESOUND": mili.awards.RESOUND.show(),

  # history
  "Roald Amundsen": hist.fig.Amundsen.show(),
  "Roald Engelbregt Gravning Amundsen": hist.fig.Amundsen,
  "Robert Scott": hist.fig.Scott.show(),
  "Robert Falcon Scott": hist.fig.Scott,
  "Sir Robert Falcon Scott": hist.fig.Scott,
  "James Ross": hist.fig.Ross.show(),
  "James Clark Ross": hist.fig.Ross,
  "Sir James Clark Ross": hist.fig.Ross,

  "Lynuca Veritori": hist.fig.Lynuca.show(),
  "Lynuca": hist.fig.Lynuca.hide(),
  "Detrin Viruna": hist.fig.Detrin.show(),
  "Detrin": hist.fig.Detrin.hide(),
  "Viruna": hist.fig.Detrin.hide(),
  "Anatrin Anaconda": hist.fig.Anatrin.show(),
  "Anatrin": hist.fig.Anatrin.hide(),

  "Alonzo Ark": hist.fig.Alonzo.show(),
  "Alonzo Altan Ark": hist.fig.Alonzo,
  "Adelina Ark": hist.fig.Adelina.show(),
  "Adelina Altan Ark": hist.fig.Adelina,

  "Historical Figures Of Antarctica": hist.stat.Figures.show("Historical Figures of Antarctica"),
  "Notable Historical Figures": hist.stat.Figures,
  "Notable Figures Of Antarctica": hist.stat.Figures,
  "Notable Figures": hist.stat.Figures,
  "Ascendant": hist.stat.Ascendant.show(),
  "Ruler": hist.stat.Ascendant,
  "King": hist.stat.Ascendant,
  "Emperor": hist.stat.Ascendant,
  "Sovereign": hist.stat.Ascendant,
  "Royalty": hist.stat.Ascendant,

  "Ancient Antarctica": hist.era.Ancient.show(),
  "Colonies Of Antarctica": hist.era.Colonies.show("Colonies of Antarctica"),
  "Ancient Anarchy": hist.era.Anarchy.show(),
  "Anarchy": hist.era.Anarchy,
  "Republic Of Antarctica": hist.era.Republic.show("Republic of Antarctica"),
  "New Antarctica": hist.era.New.show(),

  # nato
  "Aurora Australis": nato.Aurora.show(),
  "Aurora": nato.Aurora,
  "Southern Lights": nato.Aurora,

  "Photoplankton": nato.Plankton.show(),
  "Ni Coli": nato.Coli.show(),

  "Simmering Opal": nato.cryst.Opal.show(),
  "Opal": nato.cryst.Opal.hide(),
  "Trekker's Treasure": nato.cryst.Opal,
  "Antarctic Essence": nato.cryst.Essence.show(),
  "Celestial Essence": nato.cryst.Essence,
  "Essence": nato.cryst.Essence.hide(),
  "Vericium Ultri": nato.cryst.Essence,

  # misc
  "ARCANE": misc.ARCANE.show(),
  "ASCENSE": misc.ASCENSE.show(),
  "Elements": misc.ASCENSE,
  "RETINA": misc.RETINA.show(),
  "SUPCODE": misc.supcode.show("Supcode"),

  # disc
  "ADE": disc.ade.ADE.show(),
  "Bot": disc.ade.ADE,
  "ADELINE": disc.ade.Adeline.show("Adeline"),
  "Sup#0.2": disc.ade.Sup.show(),
  "Sup0.2": disc.ade.Sup,
  "SHARD": disc.ade.Shard.show(),
  "SHARD-BOT": disc.ade.Shard,
  "PENGUIN": disc.ade.Penguin.show(),
  "PENGUIN-BOT": disc.ade.Penguin,
  "ABSOLUTE": disc.ade.Absolute,

  # easter eggs
  "EASTER EGG": egg.Egg.hide(),
  "NOT SO RANDOM": egg.Rare.hide(),
  "I LOVE ANTARCTICA": egg.Epic.hide(),
  "HIDDEN SEQUENCE": egg.Legendary.hide(),
  "THE JOINING": egg.Mythical.hide(),
  "ALL HAIL PENGUIN": egg.Heavenly.hide(),
  "FUDGE YOU DELE": egg.Celestial.hide(),

  "Diamond Shard": egg.Diamond.hide(),


  # deprecated
  "ARC": item(
    title = "Antarctican Residence Core",
    caption = "[deprecated] Technological Device",
    content = "TBA",
    other = "A-CORE",
  )
}


assist = [
  "You can submit ideas using `/util idea`.",
  "If you find any bugs or missing descriptions, be sure to report it!",
  "Autocomplete can take a second to load, as the options have to be sent to from Penguin to Discord.",
  "If autocomplete fail to load, that’s probably a sign that something’s broken. Alternatively, Penguin could be down.",
  "Many autocomplete options will display randomyzed items when you haven’t typed anything yet.",
  "Many commands with a singular optional field will lookup a random item when the field is left empty.",
  "You can submit anonymous ideas when activating `/util idea` by enabling the `anonymous` option, should you wish to do so.",
  "You can view my profile using `/vita visualyze` to see global stats across all identities.",
]

aspect = [
  "69% of the world’s freshwater reserves are stored in the ancient ice of the Antarctic continent.",
  "The flag of Antarctica depicts a triangular pole against a dark blue sky, with a shadow cast upon on the white ice.",
  "The Foundation of Antarctica’s flag is actually the flag of Antarctica flipped!",
  "The Foundation of Antarctica’s flag depicts an iceberg floating among a dark blue sea, against a white sky, with dark blue structures of civilization atop it.",
  "The capital city of Antarctica is Ross City, in the Aventurina Distict.",
  "The decants and their values correspond with the time of year that they represent – for example, Vepida, the decant of warmth, is the peak of summer and the warmest decant of the year.",
  "People can still survive within the Geosphere without a CORE; it’s just colder and less comfortable.",
  "The I-CORE contains a tiny amount of Antarctic Essence.",
  "Should you decide to throw yourself at the Geosphere, which is heavily unadvised, you’ll be instantly neutralized.",
  "The words ‘Antarctic’ and ‘Antarctican’ are very similar, but have slightly different meanings. ‘Antarctic’ means relating, to the *continent* of Antarctica, while ‘Antarctican’ means relating to the *country* of Antarctica.",
  "The colour of the Antarctican flag is known as ‘Antarctican Blue’.",
  "The blue tint of the surface ice in Antarctica is known as ‘Antarctic Blue’.",
  "Aventurine is the national gemstone of Antarctica.",
  "SHARD is the 3rd generation of its Adeline, preceded by SPARK and SHIVER.",
  "PENGUIN is the second generation of its Adeline, preceded by EDEN.",
  "*Vitaline* was originally called *Lifeline*.",
  "Would you like to know about the Arctic? Well, we don’t talk about that here.",
  "The old version of the A-CORE was called the ARC.",
  "The old version of the V-CORE was called the AVA.",
]

arcane = [
  "publisher taking initiative originally in shooting writer",
  "lark circling sailor caught, a bleak prospect",
]